In [120]:
import pandas as pd
import numpy as np

In [129]:
from bs4 import BeautifulSoup
import urllib3
import os
import datetime

h = urllib3.PoolManager()
resp = h.request('GET', 'https://gogov.ru/covid-19/msk')
a = resp.data.decode('utf-8')
soup = BeautifulSoup(a, 'lxml')
date = []
quantity = []
new_cases = []
j = 0
y = 0
for tag in soup.find_all("tr"):
        x = str("{0}: {1}".format(tag.name, tag.text).strip('tr: '))
        date += [x[:8]]
        x = x[8:]
        if x != 'лучаев зараженияУмерлоВыздоровело' and len(x) > 32:
                while x[j] != '(':
                        j += 1
                quantity += [x[:j]]
        x = x[j:]
        if x != 'лучаев зараженияУмерлоВыздоровело' and len(x) > 25:
                while x[y] != ')':
                        y += 1
                new_cases += [x[1:y]]
        
        y = 0
        j = 0
date = date[1:32]
quantity = quantity[:31]
new_cases = new_cases[:31]

In [130]:
table = pd.DataFrame([quantity, new_cases], 
columns = [date])

df

,18.01.21,17.01.21,16.01.21,15.01.21,14.01.21,13.01.21,12.01.21,11.01.21,10.01.21,09.01.21,...,28.12.20,27.12.20,26.12.20,25.12.20,24.12.20,23.12.20,22.12.20,21.12.20,20.12.20,19.12.20
0,895 327,891 648,887 636,882 962,877 428,871 535,867 215,862 214,857 568,853 352,...,792 457,786 204,779 584,772 104,764 789,756 586,750 934,743 697,735 900,728 637
1,+3 679,+4 012,+4 674,+5 534,+5 893,+4 320,+5 001,+4 646,+4 216,+4 900,...,+6 253,+6 620,+7 480,+7 315,+8 203,+5 652,+7 237,+7 797,+7 263,+6 459